# Generated by Django 5.1.7 on 2025-04-29 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('num_of_likes', models.IntegerField(default=0)),
                ('num_of_comments', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('num_of_likes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stories.story')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_likes', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='stories.story')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='stories.comment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['comment'], name='stories_com_comment_21d4c0_idx'), models.Index(fields=['author'], name='stories_com_author__4a50c4_idx'), models.Index(fields=['created_at'], name='stories_com_created_db9d1e_idx')],
                'constraints': [models.UniqueConstraint(fields=('comment', 'author'), name='unique_comment_like')],
            },
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['author'], name='stories_sto_author__45d8bc_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['created_at'], name='stories_sto_created_d8706d_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['num_of_likes'], name='stories_sto_num_of__bb987b_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['story'], name='stories_com_story_i_cb7af9_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author'], name='stories_com_author__e5526b_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='stories_com_created_615d52_idx'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('story', 'author', 'content'), name='unique_comment'),
        ),
        migrations.AddIndex(
            model_name='storylike',
            index=models.Index(fields=['story'], name='stories_sto_story_i_8b2cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='storylike',
            index=models.Index(fields=['author'], name='stories_sto_author__979e87_idx'),
        ),
        migrations.AddIndex(
            model_name='storylike',
            index=models.Index(fields=['created_at'], name='stories_sto_created_1151c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='storylike',
            constraint=models.UniqueConstraint(fields=('story', 'author'), name='unique_like'),
        ),
    ]
