# Generated by Django 5.1.7 on 2025-05-07 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('city', '0001_initial'),
        ('clinic', '0003_alter_clinic_city_alter_doctor_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='city.city'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
