# Generated by Django 5.1.7 on 2025-05-13 14:38

import clinic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='certification',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=clinic.models.upload_doctor_certification),
        ),
    ]
