# Generated by Django 5.1.7 on 2025-05-02 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='city',
            field=models.ForeignKey(default='Not Specified', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='accounts.city'),
        ),
    ]
