# Generated by Django 5.1.7 on 2025-05-14 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
        ('clinic', '0002_doctor_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='city',
            field=models.ForeignKey(blank=True, choices=[('Shebin El-Kom', 'Shebin El-Kom'), ('Menouf', 'Menouf'), ('Tookh Tanbesha', 'Tookh Tanbesha'), ('Quesna', 'Quesna'), ('Berket El-Sabaa', 'Berket El-Sabaa'), ('Ashan', 'Ashan'), ('Shibra Balloula', 'Shibra Balloula'), ('Sadat City', 'Sadat City'), ('Nasr City', 'Nasr City'), ('Heliopolis', 'Heliopolis'), ('Maadi', 'Maadi'), ('Zamalek', 'Zamalek'), ('Downtown', 'Downtown'), ('New Cairo', 'New Cairo'), ('Mokattam', 'Mokattam'), ('Sheraton', 'Sheraton'), ('Garden City', 'Garden City'), ('Abbasia', 'Abbasia'), ('Smouha', 'Smouha'), ('Miami', 'Miami'), ('Roushdy', 'Roushdy'), ('Gleem', 'Gleem'), ('Stanley', 'Stanley'), ('Louran', 'Louran'), ('Al Mansheya', 'Al Mansheya'), ('Bolkly', 'Bolkly'), ('Dokki', 'Dokki'), ('Mohandeseen', 'Mohandeseen'), ('Agouza', 'Agouza'), ('Haram', 'Haram'), ('Faysal', 'Faysal'), ('October', 'October'), ('Sheikh Zayed', 'Sheikh Zayed'), ('Imbaba', 'Imbaba'), ('Not Specified', 'Not Specified')], default='Not Specified', null=True, on_delete=django.db.models.deletion.SET_NULL, to='city.city'),
        ),
    ]
