# Generated by Django 5.1.7 on 2025-05-07 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
        ('clinic', '0002_alter_doctor_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='city.city'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='city',
            field=models.ForeignKey(default='Not Specified', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='city.city'),
        ),
    ]
