# Generated by Django 5.1.7 on 2025-05-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_appointment_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='city',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
