# Generated by Django 5.1.7 on 2025-05-11 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_alter_clinic_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='clinic.doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='end_hour',
            field=models.TimeField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='start_hour',
            field=models.TimeField(blank=True, default=0, null=True),
        ),
    ]
