# Generated by Django 5.1.7 on 2025-05-11 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_doctorupdatetoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorupdatetoken',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='clinic.doctor'),
        ),
    ]
