# Generated by Django 5.1.7 on 2025-05-07 03:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(choices=[('Shebin El-Kom', 'Shebin El-Kom'), ('Menouf', 'Menouf'), ('Tookh Tanbesha', 'Tookh Tanbesha'), ('Quesna', 'Quesna'), ('Berket El-Sabaa', 'Berket El-Sabaa'), ('Ashan', 'Ashan'), ('Shibra Balloula', 'Shibra Balloula'), ('Sadat City', 'Sadat City'), ('Nasr City', 'Nasr City'), ('Heliopolis', 'Heliopolis'), ('Maadi', 'Maadi'), ('Zamalek', 'Zamalek'), ('Downtown', 'Downtown'), ('New Cairo', 'New Cairo'), ('Mokattam', 'Mokattam'), ('Sheraton', 'Sheraton'), ('Garden City', 'Garden City'), ('Abbasia', 'Abbasia'), ('Smouha', 'Smouha'), ('Miami', 'Miami'), ('Roushdy', 'Roushdy'), ('Gleem', 'Gleem'), ('Stanley', 'Stanley'), ('Louran', 'Louran'), ('Al Mansheya', 'Al Mansheya'), ('Bolkly', 'Bolkly'), ('Dokki', 'Dokki'), ('Mohandeseen', 'Mohandeseen'), ('Agouza', 'Agouza'), ('Haram', 'Haram'), ('Faysal', 'Faysal'), ('October', 'October'), ('Sheikh Zayed', 'Sheikh Zayed'), ('Imbaba', 'Imbaba'), ('Not Specified', 'Not Specified')], max_length=50)),
            ],
        ),
    ]
